#cloud-config
yum_repos:
  epel:
    name: Extra Packages for Enterprise Linux 9 - $basearch
    baseurl: https://download.fedoraproject.org/pub/epel/9/Everything/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip

runcmd:
  # Enable CRB repo (needed for some Python build deps)
  - [ bash, -lc, 'sudo dnf config-manager --set-enabled crb' ]

  # Install Ansible
  - [ bash, -lc, 'sudo yum install -y ansible']  
  - [ bash, -lc, 'ansible-galaxy collection install azure.azcollection' ]

  # Create working directory
  - [ bash, -lc, 'mkdir -p /home/ansible' ]
  - [ bash, -lc, 'chown -R ansibleadmin:ansibleadmin /home/ansible || true' ]

  # Verify ansible install
  - [ bash, -lc, 'ansible --version > /var/log/ansible-version.log 2>&1' ]
  - [ bash, -lc, 'echo \"Control node bootstrap complete\" >> /var/log/ansible-bootstrap.log' ]
