---
plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - web-rg

auth_source: auto

keyed_groups:
  - prefix: tag
    key: tags
  - prefix: location
    key: location
  - prefix: os
    key: os_type

default_host_filters:
  - powerstate == 'running'